using Jutul
# include("linalg/linear_operators.jl")
include("test_systems/runtests.jl")
include("mesh.jl")
include("embedded_meshes.jl")
include("cut_cell_meshes.jl")
include("glue_mesh.jl")
include("adjoints/utils.jl")
include("adjoints/basic_adjoint.jl")
include("adjoints/lbfgs.jl")
include("utils.jl")
include("partitioning.jl")
include("units.jl")
include("sparsity.jl")
include("nfvm.jl")
include("weno.jl")
include("vem.jl")
